<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '640de5c897a3152ffbcb29cc9aa683cb',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/cerebrum5?serverVersion=mariadb-10.4.18',
);
